export const state = {
    mode: 'text',
    text: '電気工学研究部',
    fontKey: 'sans',
    textSize: 10,
    textSpacing: -1,
    modelThickness: 3,
    svgContent: null,
    svgScale: 1.0,
    mirrorX: false,
    baseEnabled: true,
    basePadding: 2,
    baseThickness: 2,
    baseRadius: 5,
    ringEnabled: true,
    ringShape: 32,
    ringAutoY: false,
    ringX: 0,
    ringY: 11,
    ringSize: 3,
    ringTube: 1,
    ringRot: 0,
    ringReinforce: true
};
